In [2]:
from osgeo import gdal

In [3]:
roi = 'roi/guangdong_all.shp'

In [15]:
ds = gdal.Open('2001_1.pr.tif', gdal.GA_ReadOnly)
ds2 = gdal.Open('2001.LC_Type1.tif', gdal.GA_ReadOnly)

In [11]:
ds

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x0000019409C88420> >

In [12]:
arr = ds.ReadAsArray()

In [13]:
arr.shape

(1183, 1679)

In [14]:
arr

array([[-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       ...,
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.]])

In [17]:
ds.RasterXSize

1679

In [18]:
type(ds)

osgeo.gdal.Dataset

In [19]:
type(arr)

numpy.ndarray

In [1]:
import numpy as np

In [5]:
a = np.zeros((3,5,5))

In [6]:
a[0]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
a[0] = np.ones((5,5))

In [8]:
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])